apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: tomcat-pod
  name: tomcat-pod
spec:
  containers:
  - image: tomcat:latest
    name: tomcat-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
